{% set version = "1.3.6" %}

package:
  name: libvorbis
  version: "1.3.6"

source:
  url: http://downloads.xiph.org/releases/vorbis/libvorbis-{{ version }}.tar.gz
  fn: libvorbis-{{ version }}.tar.gz
  md5: 6ed40e0241089a42c48604dc00e362beee00036af2d8b3f46338031c9e0351cb


build:
  number: 0
  skip: true         # [win]

requirements:
  build:
    - toolchain
    - perl
    - yasm

extra:
  recipe-maintainers:
    - gaiar
