{% set version = "0.14.0" %}

package:
  name: libass
  version: "0.14.0"

source:
  git_url: https://github.com/libass/libass.git
  git_rev: 98727c3b78f44cb3bbc955fcf5d977ebd911d5ca

build:
  number: 0
  skip: true         # [win]

requirements:
  build:
    - toolchain3-rpi3
    - perl
    - nasm

# test:
#   commands:
#     - test -f ${PREFIX}/include/x264.h         # [unix]
#     - test -f ${PREFIX}/lib/libx264.a          # [unix]
#     - test -f ${PREFIX}/lib/libx264.dylib      # [osx]
#     - test -f ${PREFIX}/lib/libx264.so         # [linux]
#     - x264 --help                              # [unix]

about:
  home: http://www.videolan.org/developers/x264.html
  license: GPL 2
  license_file: COPYING
  summary: A free software library for encoding video streams into the H.264/MPEG-4 AVC format.

extra:
  recipe-maintainers:
    - gaiar
